#############################################################################
# Makefile for building: Punto_Navi
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  Punto_Navi.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile Punto_Navi.pro -spec linux-g++
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_PLUGIN -DQT_MULTIMEDIAWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_BLUETOOTH_LIB -DQT_NETWORK_LIB -DQT_SERIALPORT_LIB -DQT_POSITIONING_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -pthread -pthread -pthread -pthread -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1y -pthread -pthread -pthread -pthread -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Iheadunit/hu -Iheadunit/hu/generated.x64 -Iheadunit/common -I/home/windows/raspi/sysroot/usr/local/include/libusb-1.0/ -isystem /usr/include/libusb-1.0 -isystem /usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/gstreamer-1.0 -isystem /usr/include/orc-0.4 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/x86_64-linux-gnu/qt5/QtMultimedia -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtBluetooth -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtSerialPort -isystem /usr/include/x86_64-linux-gnu/qt5/QtPositioning -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Punto_Navi1.0.0
DISTDIR = /home/windows/Punto_Navi/Punto_Navi/.tmp/Punto_Navi1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu
LIBS          = $(SUBLIBS) -L/home/windows/raspi/sysroot/usr/lib/arm-linux-gnueabihf/ -lssl -lcrypto -lusb-1.0 -lgstapp-1.0 -lgstvideo-1.0 -lgstbase-1.0 -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0 -ludev -lprotobuf -pthread /usr/lib/x86_64-linux-gnu/libQt5MultimediaWidgets.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5X11Extras.so /usr/lib/x86_64-linux-gnu/libQt5Multimedia.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Bluetooth.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5SerialPort.so /usr/lib/x86_64-linux-gnu/libQt5Positioning.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = aa_headunit.cpp \
		androidauto.cpp \
		headunit.cpp \
		headunit/hu/hu_aad.cpp \
		headunit/hu/hu_aap.cpp \
		headunit/hu/hu_ssl.cpp \
		headunit/hu/hu_tcp.cpp \
		headunit/hu/hu_usb.cpp \
		headunit/hu/hu_uti.cpp \
		headunit/common/glib_utils.cpp \
		headunit/hu/generated.x64/hu.pb.cc \
		custombutton.cpp \
		hollowcircle.cpp \
		intro.cpp \
		main.cpp \
		mainwindow.cpp \
		menu.cpp \
		menuentry.cpp \
		oclock.cpp \
		settings.cpp \
		switch.cpp \
		gps_data.cpp \
		qserialgeoinfosource.cpp \
		gpsshowtime.cpp \
		timechanger.cpp qrc_resources.cpp \
		moc_aa_headunit.cpp \
		moc_androidauto.cpp \
		moc_headunit.cpp \
		moc_custombutton.cpp \
		moc_intro.cpp \
		moc_mainwindow.cpp \
		moc_menu.cpp \
		moc_menuentry.cpp \
		moc_oclock.cpp \
		moc_settings.cpp \
		moc_switch.cpp \
		moc_gps_data.cpp \
		moc_qserialgeoinfosource.cpp \
		moc_gpsshowtime.cpp \
		moc_timechanger.cpp
OBJECTS       = aa_headunit.o \
		androidauto.o \
		headunit.o \
		hu_aad.o \
		hu_aap.o \
		hu_ssl.o \
		hu_tcp.o \
		hu_usb.o \
		hu_uti.o \
		glib_utils.o \
		hu.pb.o \
		custombutton.o \
		hollowcircle.o \
		intro.o \
		main.o \
		mainwindow.o \
		menu.o \
		menuentry.o \
		oclock.o \
		settings.o \
		switch.o \
		gps_data.o \
		qserialgeoinfosource.o \
		gpsshowtime.o \
		timechanger.o \
		qrc_resources.o \
		moc_aa_headunit.o \
		moc_androidauto.o \
		moc_headunit.o \
		moc_custombutton.o \
		moc_intro.o \
		moc_mainwindow.o \
		moc_menu.o \
		moc_menuentry.o \
		moc_oclock.o \
		moc_settings.o \
		moc_switch.o \
		moc_gps_data.o \
		moc_qserialgeoinfosource.o \
		moc_gpsshowtime.o \
		moc_timechanger.o
DIST          = ../raspi/sysroot/include/QtProtobufProtobuf/QtCore.proto \
		../raspi/sysroot/include/QtProtobufProtobuf/QtGui.proto \
		config.json \
		aa_settings.ini \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Punto_Navi.pro SetManager.h \
		aa_headunit.h \
		androidauto.h \
		headunit.h \
		headunit/hu/hu_aad.h \
		headunit/hu/hu_aap.h \
		headunit/hu/hu_ssl.h \
		headunit/hu/hu_tcp.h \
		headunit/hu/hu_usb.h \
		headunit/hu/hu_uti.h \
		headunit/hu/generated.x64/hu.pb.h \
		headunit/common/glib_utils.h \
		custombutton.h \
		hollowcircle.h \
		intro.h \
		mainwindow.h \
		menu.h \
		menuentry.h \
		oclock.h \
		settings.h \
		switch.h \
		gps_data.h \
		qserialgeoinfosource.h \
		gpsshowtime.h \
		timechanger.h aa_headunit.cpp \
		androidauto.cpp \
		headunit.cpp \
		headunit/hu/hu_aad.cpp \
		headunit/hu/hu_aap.cpp \
		headunit/hu/hu_ssl.cpp \
		headunit/hu/hu_tcp.cpp \
		headunit/hu/hu_usb.cpp \
		headunit/hu/hu_uti.cpp \
		headunit/common/glib_utils.cpp \
		headunit/hu/generated.x64/hu.pb.cc \
		custombutton.cpp \
		hollowcircle.cpp \
		intro.cpp \
		main.cpp \
		mainwindow.cpp \
		menu.cpp \
		menuentry.cpp \
		oclock.cpp \
		settings.cpp \
		switch.cpp \
		gps_data.cpp \
		qserialgeoinfosource.cpp \
		gpsshowtime.cpp \
		timechanger.cpp
QMAKE_TARGET  = Punto_Navi
DESTDIR       = 
TARGET        = Punto_Navi
TARGETD       = Punto_Navi


first: all
####### Build rules

Punto_Navi: ui_aa_headunit.h ui_gpsshowtime.h ui_mainwindow.h ui_menu.h ui_settings.h ui_timechanger.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Punto_Navi.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Punto_Navi.pro \
		resources.qrc
	$(QMAKE) -o Makefile Punto_Navi.pro -spec linux-g++
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_nfc.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
Punto_Navi.pro:
resources.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile Punto_Navi.pro -spec linux-g++

qmake_all: FORCE


all: Makefile Punto_Navi

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents SetManager.h aa_headunit.h androidauto.h headunit.h headunit/hu/hu_aad.h headunit/hu/hu_aap.h headunit/hu/hu_ssl.h headunit/hu/hu_tcp.h headunit/hu/hu_usb.h headunit/hu/hu_uti.h headunit/hu/generated.x64/hu.pb.h headunit/common/glib_utils.h custombutton.h hollowcircle.h intro.h mainwindow.h menu.h menuentry.h oclock.h settings.h switch.h gps_data.h qserialgeoinfosource.h gpsshowtime.h timechanger.h $(DISTDIR)/
	$(COPY_FILE) --parents aa_headunit.cpp androidauto.cpp headunit.cpp headunit/hu/hu_aad.cpp headunit/hu/hu_aap.cpp headunit/hu/hu_ssl.cpp headunit/hu/hu_tcp.cpp headunit/hu/hu_usb.cpp headunit/hu/hu_uti.cpp headunit/common/glib_utils.cpp headunit/hu/generated.x64/hu.pb.cc custombutton.cpp hollowcircle.cpp intro.cpp main.cpp mainwindow.cpp menu.cpp menuentry.cpp oclock.cpp settings.cpp switch.cpp gps_data.cpp qserialgeoinfosource.cpp gpsshowtime.cpp timechanger.cpp $(DISTDIR)/
	$(COPY_FILE) --parents aa_headunit.ui gpsshowtime.ui mainwindow.ui menu.ui settings.ui timechanger.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		/usr/lib/qt5/bin/rcc \
		clock-face.png \
		fancy-ring.png \
		digital-7.ttf \
		img/punto-nloop.gif \
		img/stain.jpg \
		img/auto.png \
		img/fiat-logo.jpg \
		img/punto.gif \
		img/punto1.jpg \
		img/icons/bluetooth.ico \
		img/icons/player.ico \
		img/icons/settings.ico \
		img/icons/auto.ico
	/usr/lib/qt5/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++1y -pthread -pthread -pthread -pthread -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_aa_headunit.cpp moc_androidauto.cpp moc_headunit.cpp moc_custombutton.cpp moc_intro.cpp moc_mainwindow.cpp moc_menu.cpp moc_menuentry.cpp moc_oclock.cpp moc_settings.cpp moc_switch.cpp moc_gps_data.cpp moc_qserialgeoinfosource.cpp moc_gpsshowtime.cpp moc_timechanger.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_aa_headunit.cpp moc_androidauto.cpp moc_headunit.cpp moc_custombutton.cpp moc_intro.cpp moc_mainwindow.cpp moc_menu.cpp moc_menuentry.cpp moc_oclock.cpp moc_settings.cpp moc_switch.cpp moc_gps_data.cpp moc_qserialgeoinfosource.cpp moc_gpsshowtime.cpp moc_timechanger.cpp
moc_aa_headunit.cpp: aa_headunit.h \
		menuentry.h \
		androidauto.h \
		headunit.h \
		headunit/hu/hu_uti.h \
		headunit/hu/hu_aap.h \
		headunit/hu/generated.x64/hu.pb.h \
		headunit/hu/hu_ssl.h \
		headunit/common/glib_utils.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/windows/Punto_Navi/Punto_Navi/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/windows/Punto_Navi/Punto_Navi -I/home/windows/Punto_Navi/Punto_Navi/headunit/hu -I/home/windows/Punto_Navi/Punto_Navi/headunit/hu/generated.x64 -I/home/windows/Punto_Navi/Punto_Navi/headunit/common -I/home/windows/raspi/sysroot/usr/local/include/libusb-1.0 -I/usr/include/libusb-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtBluetooth -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include aa_headunit.h -o moc_aa_headunit.cpp

moc_androidauto.cpp: androidauto.h \
		headunit.h \
		headunit/hu/hu_uti.h \
		headunit/hu/hu_aap.h \
		headunit/hu/generated.x64/hu.pb.h \
		headunit/hu/hu_ssl.h \
		headunit/common/glib_utils.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/windows/Punto_Navi/Punto_Navi/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/windows/Punto_Navi/Punto_Navi -I/home/windows/Punto_Navi/Punto_Navi/headunit/hu -I/home/windows/Punto_Navi/Punto_Navi/headunit/hu/generated.x64 -I/home/windows/Punto_Navi/Punto_Navi/headunit/common -I/home/windows/raspi/sysroot/usr/local/include/libusb-1.0 -I/usr/include/libusb-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtBluetooth -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include androidauto.h -o moc_androidauto.cpp

moc_headunit.cpp: headunit.h \
		headunit/hu/hu_uti.h \
		headunit/hu/hu_aap.h \
		headunit/hu/generated.x64/hu.pb.h \
		headunit/hu/hu_ssl.h \
		headunit/common/glib_utils.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/windows/Punto_Navi/Punto_Navi/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/windows/Punto_Navi/Punto_Navi -I/home/windows/Punto_Navi/Punto_Navi/headunit/hu -I/home/windows/Punto_Navi/Punto_Navi/headunit/hu/generated.x64 -I/home/windows/Punto_Navi/Punto_Navi/headunit/common -I/home/windows/raspi/sysroot/usr/local/include/libusb-1.0 -I/usr/include/libusb-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtBluetooth -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include headunit.h -o moc_headunit.cpp

moc_custombutton.cpp: custombutton.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/windows/Punto_Navi/Punto_Navi/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/windows/Punto_Navi/Punto_Navi -I/home/windows/Punto_Navi/Punto_Navi/headunit/hu -I/home/windows/Punto_Navi/Punto_Navi/headunit/hu/generated.x64 -I/home/windows/Punto_Navi/Punto_Navi/headunit/common -I/home/windows/raspi/sysroot/usr/local/include/libusb-1.0 -I/usr/include/libusb-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtBluetooth -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include custombutton.h -o moc_custombutton.cpp

moc_intro.cpp: intro.h \
		menuentry.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/windows/Punto_Navi/Punto_Navi/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/windows/Punto_Navi/Punto_Navi -I/home/windows/Punto_Navi/Punto_Navi/headunit/hu -I/home/windows/Punto_Navi/Punto_Navi/headunit/hu/generated.x64 -I/home/windows/Punto_Navi/Punto_Navi/headunit/common -I/home/windows/raspi/sysroot/usr/local/include/libusb-1.0 -I/usr/include/libusb-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtBluetooth -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include intro.h -o moc_intro.cpp

moc_mainwindow.cpp: mainwindow.h \
		menuentry.h \
		settings.h \
		SetManager.h \
		timechanger.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/windows/Punto_Navi/Punto_Navi/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/windows/Punto_Navi/Punto_Navi -I/home/windows/Punto_Navi/Punto_Navi/headunit/hu -I/home/windows/Punto_Navi/Punto_Navi/headunit/hu/generated.x64 -I/home/windows/Punto_Navi/Punto_Navi/headunit/common -I/home/windows/raspi/sysroot/usr/local/include/libusb-1.0 -I/usr/include/libusb-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtBluetooth -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_menu.cpp: menu.h \
		menuentry.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/windows/Punto_Navi/Punto_Navi/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/windows/Punto_Navi/Punto_Navi -I/home/windows/Punto_Navi/Punto_Navi/headunit/hu -I/home/windows/Punto_Navi/Punto_Navi/headunit/hu/generated.x64 -I/home/windows/Punto_Navi/Punto_Navi/headunit/common -I/home/windows/raspi/sysroot/usr/local/include/libusb-1.0 -I/usr/include/libusb-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtBluetooth -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include menu.h -o moc_menu.cpp

moc_menuentry.cpp: menuentry.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/windows/Punto_Navi/Punto_Navi/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/windows/Punto_Navi/Punto_Navi -I/home/windows/Punto_Navi/Punto_Navi/headunit/hu -I/home/windows/Punto_Navi/Punto_Navi/headunit/hu/generated.x64 -I/home/windows/Punto_Navi/Punto_Navi/headunit/common -I/home/windows/raspi/sysroot/usr/local/include/libusb-1.0 -I/usr/include/libusb-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtBluetooth -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include menuentry.h -o moc_menuentry.cpp

moc_oclock.cpp: oclock.h \
		hollowcircle.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/windows/Punto_Navi/Punto_Navi/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/windows/Punto_Navi/Punto_Navi -I/home/windows/Punto_Navi/Punto_Navi/headunit/hu -I/home/windows/Punto_Navi/Punto_Navi/headunit/hu/generated.x64 -I/home/windows/Punto_Navi/Punto_Navi/headunit/common -I/home/windows/raspi/sysroot/usr/local/include/libusb-1.0 -I/usr/include/libusb-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtBluetooth -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include oclock.h -o moc_oclock.cpp

moc_settings.cpp: settings.h \
		menuentry.h \
		SetManager.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/windows/Punto_Navi/Punto_Navi/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/windows/Punto_Navi/Punto_Navi -I/home/windows/Punto_Navi/Punto_Navi/headunit/hu -I/home/windows/Punto_Navi/Punto_Navi/headunit/hu/generated.x64 -I/home/windows/Punto_Navi/Punto_Navi/headunit/common -I/home/windows/raspi/sysroot/usr/local/include/libusb-1.0 -I/usr/include/libusb-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtBluetooth -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include settings.h -o moc_settings.cpp

moc_switch.cpp: switch.h \
		custombutton.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/windows/Punto_Navi/Punto_Navi/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/windows/Punto_Navi/Punto_Navi -I/home/windows/Punto_Navi/Punto_Navi/headunit/hu -I/home/windows/Punto_Navi/Punto_Navi/headunit/hu/generated.x64 -I/home/windows/Punto_Navi/Punto_Navi/headunit/common -I/home/windows/raspi/sysroot/usr/local/include/libusb-1.0 -I/usr/include/libusb-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtBluetooth -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include switch.h -o moc_switch.cpp

moc_gps_data.cpp: gps_data.h \
		qserialgeoinfosource.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/windows/Punto_Navi/Punto_Navi/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/windows/Punto_Navi/Punto_Navi -I/home/windows/Punto_Navi/Punto_Navi/headunit/hu -I/home/windows/Punto_Navi/Punto_Navi/headunit/hu/generated.x64 -I/home/windows/Punto_Navi/Punto_Navi/headunit/common -I/home/windows/raspi/sysroot/usr/local/include/libusb-1.0 -I/usr/include/libusb-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtBluetooth -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include gps_data.h -o moc_gps_data.cpp

moc_qserialgeoinfosource.cpp: qserialgeoinfosource.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/windows/Punto_Navi/Punto_Navi/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/windows/Punto_Navi/Punto_Navi -I/home/windows/Punto_Navi/Punto_Navi/headunit/hu -I/home/windows/Punto_Navi/Punto_Navi/headunit/hu/generated.x64 -I/home/windows/Punto_Navi/Punto_Navi/headunit/common -I/home/windows/raspi/sysroot/usr/local/include/libusb-1.0 -I/usr/include/libusb-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtBluetooth -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include qserialgeoinfosource.h -o moc_qserialgeoinfosource.cpp

moc_gpsshowtime.cpp: gpsshowtime.h \
		menuentry.h \
		gps_data.h \
		qserialgeoinfosource.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/windows/Punto_Navi/Punto_Navi/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/windows/Punto_Navi/Punto_Navi -I/home/windows/Punto_Navi/Punto_Navi/headunit/hu -I/home/windows/Punto_Navi/Punto_Navi/headunit/hu/generated.x64 -I/home/windows/Punto_Navi/Punto_Navi/headunit/common -I/home/windows/raspi/sysroot/usr/local/include/libusb-1.0 -I/usr/include/libusb-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtBluetooth -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include gpsshowtime.h -o moc_gpsshowtime.cpp

moc_timechanger.cpp: timechanger.h \
		menuentry.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/windows/Punto_Navi/Punto_Navi/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/windows/Punto_Navi/Punto_Navi -I/home/windows/Punto_Navi/Punto_Navi/headunit/hu -I/home/windows/Punto_Navi/Punto_Navi/headunit/hu/generated.x64 -I/home/windows/Punto_Navi/Punto_Navi/headunit/common -I/home/windows/raspi/sysroot/usr/local/include/libusb-1.0 -I/usr/include/libusb-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtBluetooth -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include timechanger.h -o moc_timechanger.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_aa_headunit.h ui_gpsshowtime.h ui_mainwindow.h ui_menu.h ui_settings.h ui_timechanger.h
compiler_uic_clean:
	-$(DEL_FILE) ui_aa_headunit.h ui_gpsshowtime.h ui_mainwindow.h ui_menu.h ui_settings.h ui_timechanger.h
ui_aa_headunit.h: aa_headunit.ui \
		/usr/lib/qt5/bin/uic \
		androidauto.h \
		headunit.h \
		headunit/hu/hu_uti.h \
		headunit/hu/hu_aap.h \
		headunit/hu/generated.x64/hu.pb.h \
		headunit/hu/hu_ssl.h \
		headunit/common/glib_utils.h
	/usr/lib/qt5/bin/uic aa_headunit.ui -o ui_aa_headunit.h

ui_gpsshowtime.h: gpsshowtime.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic gpsshowtime.ui -o ui_gpsshowtime.h

ui_mainwindow.h: mainwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_menu.h: menu.ui \
		/usr/lib/qt5/bin/uic \
		oclock.h \
		hollowcircle.h
	/usr/lib/qt5/bin/uic menu.ui -o ui_menu.h

ui_settings.h: settings.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic settings.ui -o ui_settings.h

ui_timechanger.h: timechanger.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic timechanger.ui -o ui_timechanger.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

aa_headunit.o: aa_headunit.cpp aa_headunit.h \
		menuentry.h \
		androidauto.h \
		headunit.h \
		headunit/hu/hu_uti.h \
		headunit/hu/hu_aap.h \
		headunit/hu/generated.x64/hu.pb.h \
		headunit/hu/hu_ssl.h \
		headunit/common/glib_utils.h \
		ui_aa_headunit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aa_headunit.o aa_headunit.cpp

androidauto.o: androidauto.cpp androidauto.h \
		headunit.h \
		headunit/hu/hu_uti.h \
		headunit/hu/hu_aap.h \
		headunit/hu/generated.x64/hu.pb.h \
		headunit/hu/hu_ssl.h \
		headunit/common/glib_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o androidauto.o androidauto.cpp

headunit.o: headunit.cpp headunit.h \
		headunit/hu/hu_uti.h \
		headunit/hu/hu_aap.h \
		headunit/hu/generated.x64/hu.pb.h \
		headunit/hu/hu_ssl.h \
		headunit/common/glib_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o headunit.o headunit.cpp

hu_aad.o: headunit/hu/hu_aad.cpp headunit/hu/hu_uti.h \
		headunit/hu/hu_aap.h \
		headunit/hu/generated.x64/hu.pb.h \
		headunit/hu/hu_ssl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hu_aad.o headunit/hu/hu_aad.cpp

hu_aap.o: headunit/hu/hu_aap.cpp headunit/hu/hu_uti.h \
		headunit/hu/hu_ssl.h \
		headunit/hu/hu_aap.h \
		headunit/hu/generated.x64/hu.pb.h \
		headunit/hu/hu_aad.h \
		headunit/hu/hu_usb.h \
		headunit/hu/hu_tcp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hu_aap.o headunit/hu/hu_aap.cpp

hu_ssl.o: headunit/hu/hu_ssl.cpp headunit/hu/hu_uti.h \
		headunit/hu/hu_aap.h \
		headunit/hu/generated.x64/hu.pb.h \
		headunit/hu/hu_ssl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hu_ssl.o headunit/hu/hu_ssl.cpp

hu_tcp.o: headunit/hu/hu_tcp.cpp headunit/hu/hu_uti.h \
		headunit/hu/hu_tcp.h \
		headunit/hu/hu_aap.h \
		headunit/hu/generated.x64/hu.pb.h \
		headunit/hu/hu_ssl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hu_tcp.o headunit/hu/hu_tcp.cpp

hu_usb.o: headunit/hu/hu_usb.cpp headunit/hu/hu_uti.h \
		headunit/hu/hu_usb.h \
		headunit/hu/hu_aap.h \
		headunit/hu/generated.x64/hu.pb.h \
		headunit/hu/hu_ssl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hu_usb.o headunit/hu/hu_usb.cpp

hu_uti.o: headunit/hu/hu_uti.cpp headunit/hu/hu_uti.h \
		headunit/hu/generated.x64/hu.pb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hu_uti.o headunit/hu/hu_uti.cpp

glib_utils.o: headunit/common/glib_utils.cpp headunit/common/glib_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glib_utils.o headunit/common/glib_utils.cpp

hu.pb.o: headunit/hu/generated.x64/hu.pb.cc headunit/hu/generated.x64/hu.pb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hu.pb.o headunit/hu/generated.x64/hu.pb.cc

custombutton.o: custombutton.cpp custombutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o custombutton.o custombutton.cpp

hollowcircle.o: hollowcircle.cpp hollowcircle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hollowcircle.o hollowcircle.cpp

intro.o: intro.cpp intro.h \
		menuentry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o intro.o intro.cpp

main.o: main.cpp mainwindow.h \
		menuentry.h \
		settings.h \
		SetManager.h \
		timechanger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp menu.h \
		menuentry.h \
		intro.h \
		aa_headunit.h \
		androidauto.h \
		headunit.h \
		headunit/hu/hu_uti.h \
		headunit/hu/hu_aap.h \
		headunit/hu/generated.x64/hu.pb.h \
		headunit/hu/hu_ssl.h \
		headunit/common/glib_utils.h \
		gpsshowtime.h \
		gps_data.h \
		qserialgeoinfosource.h \
		mainwindow.h \
		settings.h \
		SetManager.h \
		timechanger.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

menu.o: menu.cpp menu.h \
		menuentry.h \
		ui_menu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o menu.o menu.cpp

menuentry.o: menuentry.cpp menuentry.h \
		mainwindow.h \
		settings.h \
		SetManager.h \
		timechanger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o menuentry.o menuentry.cpp

oclock.o: oclock.cpp oclock.h \
		hollowcircle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o oclock.o oclock.cpp

settings.o: settings.cpp settings.h \
		menuentry.h \
		SetManager.h \
		ui_settings.h \
		mainwindow.h \
		timechanger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o settings.cpp

switch.o: switch.cpp switch.h \
		custombutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o switch.o switch.cpp

gps_data.o: gps_data.cpp gps_data.h \
		qserialgeoinfosource.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gps_data.o gps_data.cpp

qserialgeoinfosource.o: qserialgeoinfosource.cpp qserialgeoinfosource.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qserialgeoinfosource.o qserialgeoinfosource.cpp

gpsshowtime.o: gpsshowtime.cpp gpsshowtime.h \
		menuentry.h \
		gps_data.h \
		qserialgeoinfosource.h \
		ui_gpsshowtime.h \
		mainwindow.h \
		settings.h \
		SetManager.h \
		timechanger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gpsshowtime.o gpsshowtime.cpp

timechanger.o: timechanger.cpp timechanger.h \
		menuentry.h \
		ui_timechanger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timechanger.o timechanger.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_aa_headunit.o: moc_aa_headunit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aa_headunit.o moc_aa_headunit.cpp

moc_androidauto.o: moc_androidauto.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_androidauto.o moc_androidauto.cpp

moc_headunit.o: moc_headunit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_headunit.o moc_headunit.cpp

moc_custombutton.o: moc_custombutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_custombutton.o moc_custombutton.cpp

moc_intro.o: moc_intro.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_intro.o moc_intro.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_menu.o: moc_menu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_menu.o moc_menu.cpp

moc_menuentry.o: moc_menuentry.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_menuentry.o moc_menuentry.cpp

moc_oclock.o: moc_oclock.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_oclock.o moc_oclock.cpp

moc_settings.o: moc_settings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settings.o moc_settings.cpp

moc_switch.o: moc_switch.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_switch.o moc_switch.cpp

moc_gps_data.o: moc_gps_data.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gps_data.o moc_gps_data.cpp

moc_qserialgeoinfosource.o: moc_qserialgeoinfosource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qserialgeoinfosource.o moc_qserialgeoinfosource.cpp

moc_gpsshowtime.o: moc_gpsshowtime.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gpsshowtime.o moc_gpsshowtime.cpp

moc_timechanger.o: moc_timechanger.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_timechanger.o moc_timechanger.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Punto_Navi/bin || mkdir -p $(INSTALL_ROOT)/opt/Punto_Navi/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/Punto_Navi/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/Punto_Navi/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/Punto_Navi/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Punto_Navi/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

